packages: []
catalogs:
  build:
    unbuild: ^3.5.0
  cli:
    '@antfu/nip': ^0.1.0
    bumpp: ^10.2.0
    czg: ^1.12.0
    taze: ^19.1.0
  dev:
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.18.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    find-up: ^7.0.0
    pathe: ^2.0.3
    pkg-types: ^2.2.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
  script:
    tsx: ^4.20.3
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.1.0
    '@types/semver': ^7.7.0
  utils:
    deepmerge: ^4.3.1
    fast-npm-meta: ^0.4.4
    pnpm-workspace-yaml: ^1.1.0
    semver: ^7.7.2
    yaml: ^2.8.0
