packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.3.1
    taze: ^19.7.0
  lint:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.37.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    execa: ^9.6.0
    find-up: ^8.0.0
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
    unconfig: ^7.3.3
  script:
    tsx: ^4.20.6
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.7.1
    '@types/semver': ^7.7.1
  utils:
    '@antfu/utils': ^9.3.0
    deepmerge: ^4.3.1
    detect-indent: ^7.0.2
    diff: ^8.0.2
    fast-npm-meta: ^0.4.7
    package-manager-detector: ^1.4.0
    pnpm-workspace-yaml: ^1.2.0
    semver: ^7.7.3
