packages: []
catalogs:
  build:
    unbuild: ^3.5.0
  dev:
    bumpp: ^10.1.1
    czg: ^1.11.1
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.13.1
    eslint: ^9.27.0
    lint-staged: ^16.0.0
  peer:
    '@antfu/nip': ^0.1.0
  prod:
    '@clack/prompts': ^0.10.1
    ansis: ^4.0.0
    cac: ^6.7.14
    deepmerge: ^4.3.1
    execa: ^9.5.3
    fast-npm-meta: ^0.4.2
    find-up: ^7.0.0
    pathe: ^2.0.3
    pkg-types: ^2.1.0
    pnpm-workspace-yaml: ^0.3.1
    semver: ^7.7.2
    tinyglobby: ^0.2.13
    unconfig: ^7.3.2
    yaml: ^2.8.0
  script:
    tsx: ^4.19.4
  test:
    vitest: ^3.1.3
  types:
    '@types/node': ^22.15.19
    '@types/semver': ^7.7.0
