packages: []
catalogs:
  build:
    unbuild: ^3.5.0
  cli:
    '@antfu/nip': ^0.1.0
    bumpp: ^10.1.1
    czg: ^1.11.1
    taze: ^19.1.0
  dev:
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.13.3
    eslint: ^9.28.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    find-up: ^7.0.0
    pathe: ^2.0.3
    pkg-types: ^2.1.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
  script:
    tsx: ^4.19.4
  test:
    vitest: ^3.2.1
  types:
    '@types/node': ^22.15.29
    '@types/semver': ^7.7.0
  utils:
    deepmerge: ^4.3.1
    fast-npm-meta: ^0.4.3
    pnpm-workspace-yaml: ^0.3.1
    semver: ^7.7.2
    yaml: ^2.8.0
