packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.3.1
    taze: ^19.8.1
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    find-up-simple: ^1.0.1
    package-manager-detector: ^1.5.0
    pathe: ^2.0.3
    pnpm-workspace-yaml: ^1.3.0
    tildify: ^3.0.0
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    unconfig: ^7.3.3
  npm:
    '@npmcli/config': ^10.4.2
    fast-npm-meta: ^0.4.7
    npm-package-arg: ^13.0.1
    npm-registry-fetch: ^19.0.0
  script:
    tsx: ^4.20.6
  test:
    vitest: ^4.0.3
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.9.1
    '@types/npm-package-arg': ^6.1.4
    '@types/npm-registry-fetch': ^8.0.9
    '@types/semver': ^7.7.1
  utils:
    '@antfu/utils': ^9.3.0
    deepmerge: ^4.3.1
    detect-indent: ^7.0.2
    diff: ^8.0.2
    p-retry: ^7.1.0
    semver: ^7.7.3
    ufo: ^1.6.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
