packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    taze: ^19.4.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    find-up: ^7.0.0
    pathe: ^2.0.3
    pkg-types: ^2.3.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.3
  script:
    tsx: ^4.20.5
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.3.0
    '@types/semver': ^7.7.0
  utils:
    '@antfu/utils': ^9.2.0
    deepmerge: ^4.3.1
    diff: ^8.0.2
    fast-npm-meta: ^0.4.6
    pnpm-workspace-yaml: ^1.1.1
    semver: ^7.7.2
onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
  - vsxpub
