import type { CatalogRule } from './types'

export const DEFAULT_CATALOG_RULES: CatalogRule[] = [
  {
    name: 'types',
    match: [/@types/],
    // depFields: ['devDependencies'],
    priority: 10,
  },
  {
    name: 'monorepo',
    match: [/lerna/, /nx/, /turbo/],
    priority: 20,
  },
  {
    name: 'lint',
    match: [/lint/, /prettier/, /biome/, /husky/, /git-hooks/, /cspell/],
    priority: 20,
  },
  {
    name: 'cli',
    match: [
      /changesets/,
      /release/,
      /bump/,
      /taze/,
      /check-update/,
      /commitizen/,
      /cz-git/,
      /czg/,
      /pncat/,
    ],
    priority: 20,
  },
  {
    name: 'test',
    match: [
      /vitest/,
      /jest/,
      /mocha/,
      /ava/,
      /jasmine/,
      /test-utils/,
      /testing-library/,
    ],
    priority: 30,
  },
  {
    name: 'e2e',
    match: [/cypress/, /playwright/, /puppeteer/, /nightwatch/, /webdriverio/],
    priority: 30,
  },
  {
    name: 'i18n',
    match: [/i18n/],
    priority: 40,
  },
  {
    name: 'build',
    match: [
      /vite/,
      /webpack/,
      /rollup/,
      /rolldown/,
      /tsup/,
      /tsdown/,
      /esbuild/,
      /unbuild/,
      /rspack/,
      /unplugin/,
      /build/,
    ],
    priority: 40,
  },
  {
    name: 'script',
    match: [/jiti/, /tsx/, /esno/],
    priority: 40,
  },
  {
    name: 'style',
    match: [/css/, /less/, /sass/, /autoprefixer/],
    priority: 50,
  },
  {
    name: 'network',
    match: [/websocket/, /ws/, /axios/, /fetch/, /qs/],
    priority: 50,
  },
  {
    name: 'icons',
    match: [/iconify/, /icon/, /lucide/],
    priority: 50,
  },
  {
    name: 'markdown',
    match: [/markdown-it/, /markdown/, /turndown/],
    priority: 50,
  },
  {
    name: 'syntax',
    match: [/shiki/, /prismjs/, /highlight/, /mermaid/, /katex/],
    priority: 50,
  },
  {
    name: 'tsc',
    match: [/typescript/, /tsc/, /tsconfig/],
    priority: 50,
  },
  {
    name: 'utils',
    match: [
      /lodash/,
      /ramda/,
      /zod/,
      /dayjs/,
      /semver/,
      /uuid/,
      /nanoid/,
      /string-width/,
      /magic-string/,
      /cheerio/,
      /deepmerge/,
      /defu/,
      /utils/,
      /use/,
    ],
    priority: 60,
  },
  {
    name: 'node',
    match: [
      /cac/,
      /synckit/,
      /rimraf/,
      /ora/,
      /consola/,
      /chalk/,
      /unconfig/,
      /env/,
      /path/,
      /exec/,
      /glob/,
      /resolve/,
      /ansi/,
      /prompts/,
      /find-/,
      /fs(?=-)|(?<=-)fs/,
      /pkg(?=-)|(?<=-)pkg/,
    ],
    priority: 60,
  },
  {
    name: 'frontend',
    match: [
      /nprogress/,
      /swiper/,
      /tippy/,
      /monaco/,
      /codemirror/,
      /xterm/,
      /chart/,
      /motion/,
      /d3/,
      /three/,
      /pixi/,
      /vue/,
      /pinia/,
      /react/,
      /redux/,
      /angular/,
      /svelte/,
      /antd/,
      /vant/,
      /design/,
      /element/,
      /component/,
      /(?:-ui|\/ui)/,
    ],
    priority: 60,
  },
  {
    name: 'backend',
    match: [/express/, /koa/, /hapi/, /fastify/],
    priority: 60,
  },
  {
    name: 'database',
    match: [
      /prisma/,
      /sequelize/,
      /knex/,
      /drizzle/,
      /mongo/,
      /database/,
      /datastore/,
      /sql/,
      /orm/,
    ],
    priority: 60,
  },
]
