import type { CatalogRule } from './types'

export const DEFAULT_CATALOG_RULES: CatalogRule[] = [
  {
    name: 'types',
    match: [/@types/],
    // depFields: ['devDependencies'],
    priority: 10,
  },
  {
    name: 'monorepo',
    match: [/lerna/, /turbo/, 'nx'],
    priority: 20,
  },
  {
    name: 'lint',
    match: [
      /lint/,
      /prettier/,
      /biome/,
      /dprint/,
      /knip/,
      /husky/,
      /git-hooks/,
      /cspell/,
    ],
    priority: 20,
  },
  {
    name: 'cli',
    match: [
      /changesets/,
      /release/,
      /bump/,
      /taze/,
      /check-update/,
      /commitizen/,
      /cz-git/,
      /czg/,
      /ovsx/,
      /vsce/,
      /pncat/,
      /vsxpub/,
    ],
    priority: 20,
  },
  {
    name: 'test',
    match: [
      /vitest/,
      /jest/,
      /mocha/,
      /ava/,
      /jasmine/,
      /test/,
    ],
    priority: 30,
  },
  {
    name: 'e2e',
    match: [/cypress/, /playwright/, /puppeteer/, /nightwatch/, /webdriverio/],
    priority: 30,
  },
  {
    name: 'i18n',
    match: [/i18n/],
    priority: 40,
  },
  {
    name: 'build',
    match: [
      /vite/,
      /webpack/,
      /rollup/,
      /rolldown/,
      /tsup/,
      /tsdown/,
      /rspack/,
      /unplugin/,
      /terser/,
      /napi/,
      /build/,
      /source-map/,
    ],
    priority: 40,
  },
  {
    name: 'script',
    match: ['unrun', 'esno', /jiti/, /tsx/],
    priority: 40,
  },
  {
    name: 'style',
    match: [
      'clsx',
      /css/,
      /less/,
      /sass/,
      /autoprefixer/,
      /tailwind/,
    ],
    priority: 50,
  },
  {
    name: 'network',
    match: [/axios/, /undici/, /fetch/, /websocket/, 'ws', 'qs'],
    priority: 50,
  },
  {
    name: 'parser',
    match: [
      /babel/,
      /swc/,
      /oxc/,
      /acorn/,
      /buble/,
      /esprima/,
      /mdast/,
      /micromark/,
      /remark/,
      /marked/,
      /([/-]|^)ast([/-]|$)/,
    ],
    priority: 50,
  },
  {
    name: 'icons',
    match: [/iconify/, /icon/, /lucide/],
    priority: 50,
  },
  {
    name: 'markdown',
    match: [/markdown/, /turndown/],
    priority: 50,
  },
  {
    name: 'vscode',
    match: [/vscode/],
    priority: 50,
  },
  {
    name: 'raycast',
    match: [/raycast/],
    priority: 50,
  },
  {
    name: 'syntax',
    match: [/shiki/, /prismjs/, /highlight/, /mermaid/, /katex/],
    priority: 50,
  },
  {
    name: 'tsc',
    match: [/typescript/, /tsc/, /tsconfig/],
    priority: 50,
  },
  {
    name: 'utils',
    match: [
      'debug',
      'scule',
      'diff',
      'detect-indent',
      'ufo',
      'hookable',
      /lodash/,
      /ramda/,
      /zod/,
      /ajv/,
      /dayjs/,
      /semver/,
      /uuid/,
      /nanoid/,
      /string-width/,
      /magic-string/,
      /picomatch/,
      /micromatch/,
      /cheerio/,
      /deepmerge/,
      /defu/,
      /lru-cache/,
      /utils/,
      /@vueuse\//,
      /^use[A-Z]/,
      /^p-/,
    ],
    priority: 60,
  },
  {
    name: 'node',
    match: [
      'cac',
      'synckit',
      'signal-exit',
      'consola',
      'unconfig',
      'empathic',
      'tildify',
      'restore-cursor',
      'exsolve',
      /chokidar/,
      /rimraf/,
      /zip/,
      /tar/,
      /fzf/,
      /ora/,
      /chalk/,
      /env/,
      /path/,
      /exec/,
      /glob/,
      /resolve/,
      /ansi/,
      /prompts/,
      /kill/,
      /cli-/,
      /find-/,
      /fs(?=-)|(?<=-)fs/,
      /pkg(?=-)|(?<=-)pkg/,
    ],
    priority: 60,
  },
  {
    name: 'frontend',
    match: [
      /nprogress/,
      /swiper/,
      /tippy/,
      /monaco/,
      /codemirror/,
      /xterm/,
      /chart/,
      /motion/,
      /jsonform/,
      /d3/,
      /three/,
      /pixi/,
      /vue/,
      /pinia/,
      /react/,
      /redux/,
      /angular/,
      /svelte/,
      /antd/,
      /vant/,
      /design/,
      /element/,
      /component/,
      /(?:-ui|\/ui)/,
    ],
    priority: 60,
  },
  {
    name: 'backend',
    match: [/express/, /koa/, /hapi/, /fastify/],
    priority: 60,
  },
  {
    name: 'database',
    match: [
      /prisma/,
      /sequelize/,
      /knex/,
      /drizzle/,
      /mongo/,
      /database/,
      /datastore/,
      /sql/,
      /orm/,
    ],
    priority: 60,
  },
]
